import AppKit

struct CapturedContent {
    enum Payload {
        case text(String, TextSubtype?)
        case image(png: Data, width: Int, height: Int)
        case fileURLs([URL])
    }

    let payload: Payload
    let contentHash: String
    let byteSize: Int
}

enum PasteboardClassifier {
    /// Written alongside our own pasteboard writes so the monitor never
    /// re-captures them, immune to changeCount races.
    static let selfMarker = NSPasteboard.PasteboardType("com.stevemurr.clipboard.self")

    private static let skipTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        selfMarker,
    ]

    private static let imageTypesToNormalize: [NSPasteboard.PasteboardType] = [
        .tiff,
        NSPasteboard.PasteboardType("public.jpeg"),
        NSPasteboard.PasteboardType("public.heic"),
        NSPasteboard.PasteboardType("public.heif"),
        NSPasteboard.PasteboardType("com.compuserve.gif"),
        NSPasteboard.PasteboardType("org.webmproject.webp"),
    ]

    static func classify(_ pasteboard: NSPasteboard) -> CapturedContent? {
        guard let types = pasteboard.types else { return nil }
        guard !skipTypes.contains(where: types.contains) else { return nil }

        // File URLs first: Finder puts both a file URL and image data on the
        // pasteboard when copying an image file — the file identity wins.
        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            return CapturedContent(
                payload: .fileURLs(urls),
                contentHash: Hashing.sha256(fileURLs: urls),
                byteSize: urls.reduce(0) { $0 + fileSize(of: $1) }
            )
        }

        // Prefer PNG as-is (no recompression); normalize other common bitmap
        // flavors to PNG so storage, hashing, and Quick Look see one format.
        if let png = pasteboard.data(forType: .png),
           let rep = NSBitmapImageRep(data: png) {
            return CapturedContent(
                payload: .image(png: png, width: rep.pixelsWide, height: rep.pixelsHigh),
                contentHash: Hashing.sha256(png),
                byteSize: png.count
            )
        }
        for type in imageTypesToNormalize {
            if let sourceData = pasteboard.data(forType: type),
               let rep = NSBitmapImageRep(data: sourceData),
               let png = rep.representation(using: .png, properties: [:]) {
                return CapturedContent(
                    payload: .image(png: png, width: rep.pixelsWide, height: rep.pixelsHigh),
                    contentHash: Hashing.sha256(png),
                    byteSize: png.count
                )
            }
        }

        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return CapturedContent(
                payload: .text(string, detectSubtype(string)),
                contentHash: Hashing.sha256(string),
                byteSize: string.utf8.count
            )
        }

        return nil
    }

    private static func detectSubtype(_ string: String) -> TextSubtype? {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        if isLink(trimmed) { return .link }
        if ColorParser.isColorString(trimmed) { return .color }
        return nil
    }

    private static func isLink(_ trimmed: String) -> Bool {
        guard !trimmed.isEmpty,
              trimmed.rangeOfCharacter(from: .whitespacesAndNewlines) == nil,
              let url = URL(string: trimmed),
              let scheme = url.scheme?.lowercased(),
              scheme == "http" || scheme == "https",
              url.host != nil
        else { return false }
        return true
    }

    private static func fileSize(of url: URL) -> Int {
        (try? FileManager.default.attributesOfItem(atPath: url.path))?[.size] as? Int ?? 0
    }
}
